### ISSUE TITLE
How to install bcl2fastq2 on Macos

### ISSUE THREAD

**Issue by falsetry1514** [rajewsky-lab/spacemake#120]
I want to install spacemake on mac, but I noticed that bcl2fastq2 seems to only run on Linux. Could it install on Macos?

**Comment by mschilli87** [comment]
@falsetry1514: I guess you'd have to ask Illumina, who developed bcl2fastq and not some random unrelated poeple who are just using it in their pipeline. 😉

**Comment by nukappa** [comment]
Hi @falsetry1514 , thanks for the interest. We haven't tested installing spacemake on Mac due to difficulties of binaries etc (for instance bcl2fastq as you wrote). Also keep in mind that you'd need at least about ~32GB of RAM to run spacemake on a human/mouse sample (this is roughly what STAR requires for aligning the reads).

**Comment by falsetry1514** [comment]
Okay, thanks for advise. I will try to run the steps that use bcl2fastq in Linux and run the other step on macos

**Comment by nukappa** [comment]
You only need bcl2fastq to demultiplex your samples. After that, you can setup your projects in spacemake by adding them and providing the `.fastq` files you just demultiplexed.

I'll close this issue now.
