### ISSUE TITLE
Update_sample requires species parameter

### ISSUE THREAD

**Issue by nukappa** [rajewsky-lab/spacemake#45]
After some commit the `update_sample` command now requires the `--species` parameter to run, otherwise throws an error, even if the species is already defined for the sample.

**Comment by nukappa** [comment]
In addition, it changes the `map_strategy` if that is not defined.

**Comment by marvin-jens** [comment]
fixed by commit 1bc2be0 . map_strategy is only inferred from species when we *add* a new sample. In that case --species is  a required argument and all is well. For updates, map_strategy is not changed from None (which means 'don't change the stored value') unless we in fact want to update via --map_strategy ... . Unittest has been added
